# Generated by Django 5.2.2 on 2025-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('rrhh', 'Recursos Humanos'), ('jefe_patio', 'Jefe de Patio'), ('Vendedor', 'Vendedor'), ('Operador', 'Operador'), ('Supervisor', 'Supervisor'), ('Encargado', 'Encargado'), ('Tecnico', 'Técnico'), ('Gerente', 'Gerente'), ('Otro', 'Otro')], max_length=20),
        ),
    ]
