# Generated by Django 5.2.1 on 2025-05-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together={('usuario', 'timestamp', 'estado')},
        ),
    ]
