# Generated by Django 5.2.1 on 2025-05-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariobiometrico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuariobiometrico',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariobiometrico',
            name='privilegio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuariobiometrico',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
