# Generated by Django 5.2.2 on 2025-06-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_customuser_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariobiometrico',
            old_name='user_id',
            new_name='user',
        ),
    ]
