# Generated by Django 5.2.2 on 2025-09-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_registroasistencia_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornadalaboral',
            options={'verbose_name': 'Jornada Laboral', 'verbose_name_plural': 'Jornadas Laborales'},
        ),
        migrations.AlterModelOptions(
            name='registroasistencia',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Registro de Asistencia', 'verbose_name_plural': 'Registros de Asistencia'},
        ),
        migrations.AddField(
            model_name='jornadalaboral',
            name='es_nocturno',
            field=models.BooleanField(default=False, help_text='Indica si es turno nocturno (cruza medianoche)'),
        ),
        migrations.AddField(
            model_name='jornadalaboral',
            name='horas_normales',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Horas normales de trabajo para esta jornada', max_digits=4),
        ),
        migrations.AddField(
            model_name='jornadalaboral',
            name='tipo_jornada',
            field=models.CharField(choices=[('manana', 'Mañana (6:00 - 14:00)'), ('tarde', 'Tarde (14:00 - 22:00)'), ('nocturno', 'Nocturno (22:00 - 6:00)'), ('personalizada', 'Personalizada')], default='personalizada', max_length=15),
        ),
    ]
