# Generated by Django 5.2.1 on 2025-06-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_usuariobiometrico_activo_usuariobiometrico_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariobiometrico',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariobiometrico',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
