# Generated by Django 5.2.2 on 2025-06-17 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_usuariobiometrico_estacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UsuarioBiometrico', to='API.estacionservico'),
        ),
    ]
