# Generated by Django 5.2.2 on 2025-06-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_user_id_usuariobiometrico_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstacionServico',
            new_name='EstacionServicio',
        ),
    ]
