# Generated by Django 5.2.1 on 2025-06-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_usuariobiometrico_apellido_usuariobiometrico_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
    ]
