# Generated by Django 5.2.2 on 2025-09-09 15:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_jornadalaboral_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroasistencia',
            options={'ordering': ['-id'], 'verbose_name': 'Registro de Asistencia', 'verbose_name_plural': 'Registros de Asistencia'},
        ),
        migrations.CreateModel(
            name='JornadaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha en que inicia la jornada especial')),
                ('fecha_fin', models.DateField(help_text='Fecha en que termina la jornada especial (puede ser al día siguiente)')),
                ('hora_inicio_programada', models.TimeField(help_text='Hora programada de inicio de la jornada especial')),
                ('hora_fin_programada', models.TimeField(help_text='Hora programada de fin de la jornada especial')),
                ('horas_programadas', models.DecimalField(decimal_places=2, default=12.0, help_text='Horas programadas para esta jornada especial', max_digits=4)),
                ('fecha_aprobacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se aprobó esta jornada especial')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la jornada especial está activa')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la jornada especial', null=True)),
                ('aprobada_por', models.ForeignKey(help_text='Jefe de patio que aprobó esta jornada especial', limit_choices_to={'rol': 'jefe_patio'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_especiales', to='API.usuariobiometrico')),
            ],
            options={
                'verbose_name': 'Jornada Especial',
                'verbose_name_plural': 'Jornadas Especiales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
