# Generated by Django 5.2.2 on 2025-06-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_estacionservico_estacionservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariobiometrico',
            name='biometrico_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuariobiometrico',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
