# Generated by Django 5.2.2 on 2025-06-12 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_estacionservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
