# Generated by Django 5.2.2 on 2025-09-09 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_registroasistencia_options_jornadaespecial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feriado Nacional',
                'verbose_name_plural': 'Feriados Nacionales',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='TarifaHoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diurno', 'Diurno'), ('nocturno', 'Nocturno'), ('feriado_diurno', 'Feriado Diurno'), ('feriado_nocturno', 'Feriado Nocturno')], max_length=20, unique=True)),
                ('tarifa_por_hora', models.DecimalField(decimal_places=2, help_text='Tarifa en pesos por hora extra', max_digits=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa Hora Extra',
                'verbose_name_plural': 'Tarifas Horas Extras',
            },
        ),
        migrations.CreateModel(
            name='ResumenSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_semana', models.DateField(help_text='Domingo que inicia la semana')),
                ('fecha_fin_semana', models.DateField(help_text='Lunes que termina la semana')),
                ('horas_normales', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('horas_extra_diurno', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('horas_extra_nocturno', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('horas_extra_feriado_diurno', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('horas_extra_feriado_nocturno', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_horas_trabajadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_horas_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('costo_horas_extra_diurno', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_horas_extra_nocturno', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_horas_extra_feriado_diurno', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_horas_extra_feriado_nocturno', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_total_horas_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_semanales', to='API.usuariobiometrico')),
            ],
            options={
                'verbose_name': 'Resumen Semanal',
                'verbose_name_plural': 'Resúmenes Semanales',
                'ordering': ['-fecha_inicio_semana', 'empleado__nombre'],
                'unique_together': {('empleado', 'fecha_inicio_semana')},
            },
        ),
    ]
