# Generated by Django 5.2.2 on 2025-06-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_usuariobiometrico_biometrico_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariobiometrico',
            name='user',
        ),
    ]
