# Generated by Django 5.2.2 on 2025-06-17 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_registroasistencia_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariobiometrico',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='usuariobiometrico',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_biometrico', to=settings.AUTH_USER_MODEL),
        ),
    ]
