# Generated by Django 5.2.2 on 2025-09-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_feriadonacional_tarifahoraextra_resumensemanal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariobiometrico',
            name='cedula',
        ),
    ]
