# Generated by Django 5.2.2 on 2025-06-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_usuariobiometrico_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='aprobado',
            field=models.BooleanField(blank=True, default=None, help_text='Aprobación de horas extra por el jefe de patio', null=True),
        ),
    ]
