# Generated by Django 5.2.2 on 2025-09-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_usuariobiometrico_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadalaboral',
            name='tipo_jornada',
            field=models.CharField(choices=[('manana', 'Mañana (7:00 - 14:00)'), ('tarde', 'Tarde (14:00 - 22:00)'), ('nocturno', 'Nocturno (22:00 - 7:00)')], default='personalizada', max_length=15),
        ),
    ]
