# Generated by Django 5.2.2 on 2025-07-01 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_registroasistencia_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionservicio',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefe_de_patio', to=settings.AUTH_USER_MODEL),
        ),
    ]
