# Generated by Django 5.2.2 on 2025-07-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_estacionservicio_jefe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariobiometrico',
            old_name='dni',
            new_name='cedula',
        ),
    ]
